name: Generate ASCII Artwork
on: push
jobs:
 ascii_job:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: list files before run
      run: ls -ltra
    - name: Run Script
      run: ./ascii.sh
    
      
    


